version: '2'

services:
    db:
        image: mariadb:10.2
        networks:
            - moodle_network
        env_file: 
            - .env
        volumes:
            - ./data/mysql:/var/lib/mysql
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        depends_on: 
            - moodle
        volumes: 
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - moodle_network
    moodle:
        image: moodle:base
        build: .
        depends_on:
            - db
            - redis
        networks:
            - moodle_network
        env_file: 
            - .env
        volumes: 
            - ./data/moodle:/var/www/moodledata
            - ./moodle:/var/www/html
            - ./etc/moodle/config.php:/var/www/html/config.php
    redis:
        image: redis:5-alpine
        entrypoint: redis-server --appendonly yes
        expose:
            - 6379
        networks:
            - moodle_network
        volumes:
            - ./data/redis:/data
networks:
    moodle_network:
        driver: bridge